const translations = {
    tl: {
        "Where is this?":"Saan ito?",
        "How much is the fare?":"Magkano ang pamasahe?",
        "Delicious":"Masarap",
        "What is your name?":"Ano ang pangalan mo?",
        "How are you?":"Kumusta ka?",
        "I have a question":"Meron akong tanong",
        "Can you please take a picture of me?":"Pwede mo akong kuhaan ng litrato?",
        "How much is this?":"Magkano ito?",
        "Thank you":"Salamat",
        "Did you eat?":"Kumain kana?",
        "I need help":"Kailangan ko ng tulong",
        "Goodbye":"Paalam",
        "Excuse me":"Pasintabi po",
        "Good morning":"Magandang Umaga",
        "Good afternoon":"Magandang Hapon",
        "Good evening":"Magandang Gabi",
        "I love you":"Mahal Kita",
        "I don't understand":"Hindi kita maintindihan",
        "You're welcome":"Walang anuman",
        "Nice to meet you":"Ikinagagalak kitang makilala",
        "I'm hungry":"Ako ay nagugutom",
        "No problem":"Walang Problema",
        "How old are you?":"Ilang taon kana?",
        "Where is the restroom?":"Saan ang banyo?",
        "I feel sick":"Masama ang pakiramdam ko",
        "I have some trouble":"Mayroon akong problema",
        "I want a translator":"Gusto ko ng taga-translate",
        "It hurts":"Masakit",
        "Please call a doctor":"Pakitawag ang doktor",
        "May I have the bill?":"Maaari ko bang makuha ang bayarin?"    
    },

    ilo: {
      "Where is this?":"Sadino iyan?",
      "How much is the fare?":"Magkano ti pamasahe?",
      "Delicious":"Naimas",
      "What is your name?":"Ania ti nagan mo?",
      "How are you?":"Kasatno ka?",
      "I have a question":"Adda dak met laeng saludsod",
      "Can you please take a picture of me?":"Mabalin ak agpa-picture?",
      "How much is this?":"Sagmano daytoy?",
      "Thank you":"Agyaman ak",
      "Did you eat?":"Nangan kan?",
      "I need help":"Kailangan ko ti tulong yo",
      "Goodbye":"Adiyo",
      "Excuse me":"Pagdespensarem apo",
      "Good morning":"Naibbag nga bigat",
      "Good afternoon":"Naimbag nga malem",
      "Good evening":"Naimbag nga rabii",
      "I love you":"Ayyeknak ka",
      "I don't understand":"Dyak maawatan",
      "You're welcome":"Awan problema",
      "Nice to meet you":"Naimsem ti makilala ka",
      "I'm hungry":"Mabisin ak",
      "No problem":"Awan problema",
      "How old are you?":"Mano tawon mon?",
      "Where is the restroom?":"Sadino ti banyo?",
      "I feel sick":"Madi iti bagik",
      "I have some trouble":"Adda problemak",
      "I want a translator":"Kayat ko ti magunta ti translator",
      "It hurts":"Masakit",
      "Please call a doctor":"Paki-ayaban ti doktor",
      "May I have the bill?":"Paki-abot man ti bayaran"    
  },
  hil:{
    "Where is this?":"Sa diin ini?",
    "How much is the fare?":"Pila ang plete?",
    "Delicious":"Namit",
    "What is your name?":"Ano ang imo ngalan?",
    "How are you?":"Kamusta ka?",
    "I have a question":"May pamangkot ako",
    "Can you please take a picture of me?":"Pwede bala ako magpa-picture?",
    "How much is this?":"Pila ini?",
    "Thankyou":"Salamat",
    "Did you eat?":"Nakakaon ka na?",
    "I need help":"Kinahanglan ko sang bulig",
    "Goodbye":"Paalam",
    "Excuse me":"Pasensiya gid",
    "Good morning":"Maayong aga",
    "Good afternoon":"Maayong hapon",
    "Good evening":"Maayong gab-i",
    "I love you":"Palangga ka nako",
    "I don't understand":"Indi ko mahangpan",
    "You're welcome":"Wala 'y problema",
    "Nice to meet you":"Maayo nga makilala ka",
    "I'm hungry":"Gutom ako",
    "No problem":"Wala 'y problema",
    "How old are you?":"Pila ang imo edad?",
    "Where is the restroom?":"Sa diin ang banyo?",
    "I feel sick":"Masakiton ako",
    "I have some trouble":"May problema ako",
    "I want a translator":"Gusto ko sang translator",
    "It hurts":"Masakit gid",
    "Please call a doctor":"Palihog tawagi ang doktorm",
    "May I have the bill?":"Pwede ko makuha ang bayad?"
   },
   war:{
    "Where is this?":"Hain ini?",
    "How much is the fare?":"Pira an pamasahe?",
    "Delicious":"Manamit",
    "What is your name?":"Ano an imo ngaran?",
    "How are you?":"Kumusta ka?",
    "I have a question":"May pakiana ako",
    "Can you please take a picture of me?":"Pwede ba ako magpapicture?",
    "How much is this?":"Pira ini?",
    "Thankyou":"Salamat",
    "Did you eat?":"Nakaon ka na ba?",
    "I need help":"Kinahanglan ko hin bulig",
    "Goodbye":"Paalam",
    "Excuse me":"pasayloa ako",
    "Good morning":"Maupay nga aga",
    "Good afternoon":"Maupay nga hapon",
    "Good evening":"Maupay nga gab-i",
    "I love you":"Nahigugma ako ha imo",
    "I do't understand":"Waray ako nakasabot",
    "You're welcome":"Waray problema",
    "Nice to meet you":"Maupay nga makilala ka",
    "I'm hungry":"Gutom ako",
    "No problem":"Waray problema",
    "How old are you?":"Pila an imo edad?",
    "Where is the restroom?":"Hain an banyo?",
    "I feel sick":"Masakiton ako",
    "I have some trouble":"May problema ako",
    "I want a translator":"Gusto ko hin translator",
    "It hurts":"Nasakitan ako",
    "Please call a doctor":"Palihog tawagi an doktor",
    "May I have the bill?":"Pwede ko ba makuha an bayaran?"
   },
   
   bik:{
    "Where is this?":"Sain ini",
    "How much is the fare?":"Magkano an pamasahe?",
    "Delicious":"Masiram",
    "What is your name?":"Ano an ngaran mo?",
    "How are you?":"Kumusta ka?",
    "I have a question":"Mayo akong hapot",
    "Can you please take a picture of me?":"Puedo mo ako kuhaan nin retrato?",
    "How much is this?":"Gurano ini?",
    "Thankyou":"Salamat",
    "Did you eat?":"Nakaon ka na ba?",
    "I need help":"Kaipuhan ko nin tabang",
    "Goodbye":"Paaram",
    "Excuse me":"Tabi",
    "Good morning":"Marhay na aga",
    "Good afternoon":"Maray na hapon",
    "Good evening":"Marhay na banggi",
    "I love you":"Namomotan taka",
    "I don't understand":"Dai ko masabutan",
    "You're welcome":"Daing anuman",
    "Nice to meet you":"Maogma ako sa satuyang pagmidbidan",
    "I'm hungry":"Gutom na ako",
    "No problem":"Mayo problema",
    "How old are you?":"Pirang taon ka na?",
    "Where is the restroom?":"sain ang kasilyas",
    "I feel sick":"pag mati ko may ilang ko",
    "I have some trouble":"Mayo ako problema",
    "I want a translator":"Muya ko nin tagapagsalin",
    "It hurts":"Makulog",
    "Please call a doctor":"Mag apod kang doktor",
    "May I have the bill?":"Pwede ko na tabi makua ang bayadan"
   },
    

    pam: {
      "Where is this?": "Nunu ya iti?",
      "How much is the fare?": "Magkano ya pamasahe?",
      "Delicious": "Masarap",
      "What is your name?": "Nung la reng lagyu mu?",
      "How are you?": "Kamusta ka?",
      "I have a question": "Mayo kung tantungan",
      "Can you please take a picture of me?": "Paki-retrato mu ku",
      "How much is this?": "Magkano ya iti?",
      "Thank you": "Salamat",
      "Did you eat?": "Mangan ka na?",
      "I need help": "Mangailangan ku ning tulung",
      "Goodbye": "Paalam",
      "Excuse me": "Pasensya na",
      "Good morning": "Mayap a umaga",
      "Good afternoon": "Mayap a aldo",
      "Good evening": "Mayap a gabii",
      "I love you": "Alug ku ka",
      "I don't understand": "E ku intindi",
      "You're welcome": "Maligayang pagsalubong",
      "Nice to meet you": "Maligayang makabalubalu ka",
      "I'm hungry": "Gutom ku",
      "No problem": "Alang problema",
      "How old are you?": "Pilubungan mu na?",
      "Where is the restroom?": "Nunu ya ing banyo?",
      "I feel sick": "Sakit ku",
      "I have some trouble": "May problema ku",
      "I want a translator": "Mangailangan ku ning tradutor",
      "It hurts": "Masakit",
      "Please call a doctor": "Paki-tawag yang doktor",
      "May I have the bill?": "Paki-dala yang bayaran"
    },
  
    pang: {
      "Where is this?": "Diin iyan?",
      "How much is the fare?": "Magkano so pamasahe?",
      "Delicious": "Sarap",
      "What is your name?": "Antoy ngaran mo?",
      "How are you?": "Kamusta ka?",
      "I have a question": "Ayu so ermen ko",
      "Can you please take a picture of me?": "Paki-picturean mo ak",
      "How much is this?": "Magkano iyan?",
      "Thank you": "Salamat",
      "Did you eat?": "Nanginan ka la?",
      "I need help": "Kaukolan ko so tulong",
      "Goodbye": "Agyaman po",
      "Excuse me": "Paki-excusa",
      "Good morning": "Maimung agaw",
      "Good afternoon": "Maung aldaw",
      "Good evening": "Maung rabi",
      "I love you": "Alayew ta ka",
      "I don't understand": "Ag ko ayalan",
      "You're welcome": "Agyaman ka",
      "Nice to meet you": "Maimung makilala ka",
      "I'm hungry": "Gutom ak",
      "No problem": "Angga'y problema",
      "How old are you?": "Pira so edad mo?",
      "Where is the restroom?": "Diin so CR?",
      "I feel sick": "Masakit so limak ko",
      "I have some trouble": "Ayu so problema ko",
      "I want a translator": "Kaukolan ko so translator",
      "It hurts": "Sakit",
      "Please call a doctor": "Paki-tawag so doktor",
      "May I have the bill?": "Pakiabot naman po so bayaran"
    },
  
    mrw: {
      "Where is this?": "Antaw sa?",
      "How much is the fare?": "Pilan ka kwarta sa pasahi?",
      "Delicious": "Mapagisa",
      "What is your name?": "Antaw ka ngaran o?",
      "How are you?": "Kumpay ka?",
      "I have a question": "Tano-an ako",
      "Can you please take a picture of me?": "Ago ba makapito ka ng gamaran sa?",
      "How much is this?": "Pilan sa?",
      "Thank you": "Magsukul",
      "Did you eat?": "Nakaen ka na?",
      "I need help": "Kikinahanglan ako o tabang",
      "Goodbye": "Ma-a so balo",
      "Excuse me": "Kiyasalamala",
      "Good morning": "Marhay nga kaagaw",
      "Good afternoon": "Marhay nga kasilo",
      "Good evening": "Marhay nga Kagabi",
      "I love you": "Phakatapo ka",
      "I don't understand": "Adik a pegkapiya ka",
      "You're welcome": "Waya sa problema",
      "Nice to meet you": "Marheya kaisa na pegkilala ka",
      "I'm hungry": "Pegkakaen ako",
      "No problem": "Waya a Problema",
      "How old are you?": "Pira ka agoy ka na?",
      "Where is the restroom?": "Antaw so banyo?",
      "I feel sick": "Waya a mapia so pegkatempa ko",
      "I have some trouble": "Saguna ako a problema",
      "I want a translator": "Suka a pegka-translator",
      "It hurts": "Sedsa",
      "Please call a doctor": "Sa a kaneng so doktor",
      "May I have the bill?": "Ago ba makaangkon ako sa bayad?"
    },
  
    ceb: {
      "Where is this?": "Asa ni?",
      "How much is the fare?": "Pila ang plete?",
      "Delicious": "Lamian",
      "What is your name?": "Unsa imong pangalan?",
      "How are you?": "Kumusta ka?",
      "I have a question": "May pangutana ko",
      "Can you please take a picture of me?": "Pwede nimo kuhaan ko og litrato?",
      "How much is this?": "Pila ni?",
      "Thank you": "Salamat",
      "Did you eat?": "Nakakaon ka na lab?",
      "I need help": "Kinahanglan ko og tabang",
      "Goodbye": "Paalam",
      "Excuse me": "Pasayloa ko",
      "Good morning": "Maayong buntag",
      "Good afternoon": "Maayong hapon",
      "Good evening":"Maayong gabii",
      "I love you": "Gihigugma tika",
      "I don't understand": "Dili ko kasabot",
      "You're welcome": "Walá'y sapayan",
      "Nice to meet you": "Kalipay kong makaila nimo",
      "I'm hungry": "Gutom ko",
      "No problem": "Wala'y problema",
      "How old are you?": "Pila imong edad?",
      "Where is the restroom?": "Asa ang kasilyas?",
      "I feel sick": "Sakit akong pamati",
      "I have some trouble": "Adunay problema ko",
      "I want a translator": "Gusto ko ug translator",
      "It hurts": "Sakit",
      "Please call a doctor": "Palihog tawag og doktor",
      "May I have the bill?": "Pwede ko makuha sa resibo?"
    }
  
  };
  
 // Event listener for the translate button
 document.getElementById("translateButton").addEventListener("click", () => {
  const phrase = document.getElementById("phraseSelect").value;
  const language = document.getElementById("languageSelect").value;

  const translatedText = translations[language]?.[phrase] || "Translation not available.";
  document.getElementById("outputText").textContent = translatedText;
});

  
  document.getElementById("darkModeToggle").addEventListener("change", (event) => {
    if (event.target.checked) {
      document.body.classList.add("dark-mode");
    } else {
      document.body.classList.remove("dark-mode");
    }
  });
  
  
  